

name: Test w/Dashboard Recording

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-private-key: ${{ secrets.SSH_KEY}}
          repo-mappings: github.com/northhighland-seas/seas-cypress-cucumber-utilities-js

      - name: Decrypt cypress.env.json File
        run: gpg --decrypt --passphrase abc123 --batch -o cypress.env.json cypress.env.json.gpg

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # CYPRESS_TEST_CONFIGURATION: ${{ secrets.TEST_CONFIGURATION }}
