

name: Test w/Dashboard Recording

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   ssh-private-key: ${{ secrets.SSH_KEY }}
        #   repo-mappings: get@github.com/northhighland-seas/seas-cypress-cucumber-preprocessor

      - name: Hack cypress-cucumber-preprocessor pt 1/2
        run: mkdir -p node_modules/cypress-cucumber-preprocessor/lib

      - name: Hack cypress-cucumber-preprocessor pt 2/2
        run: cp .misc/getStepDefinitionsPaths.js node_modules/cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.js

      - name: Decrypt cypress.env.json File
        run: gpg --decrypt --passphrase ${{ secrets.GPG_PASSPHARSE }} --batch -o cypress.env.json cypress.env.json.gpg

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: xxx
        run: cat node_modules/cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.js
