

name: Test w/Dashboard Recording

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          repo-mappings: github.com/northhighland-seas/seas-cypress-cucumber-utilities-js

      - name: Decrypt cypress.env.json File
        run: gpg --decrypt --passphrase 0a7f38dc-d6b5-11ec-9d64-0242ac120002 --batch -o cypress.env.json cypress.env.json.gpg

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
