

name: Test w/Dashboard Recording

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-private-key: ${{ secrets.SSH_KEY}}
          repo-mappings: github.com/northhighland-seas/seas-cypress-cucumber-utilities-js

      - name: Create cypress.env.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.TEST_CONFIGURTION }}
          # json: '{ "TEST_CONFIGURATION": { "query": "swiss cheese" } }'

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
 